### ISSUE TITLE
Avaliação de Banco de Dados

### ISSUE THREAD

**Issue by JorgeEduard** [iurygdeoliveira/MySQL#1]
Professor quase nenhuma dessas questões foram explicadas nas suas vídeo aulas, não estou conseguindo resolver.

**Comment by iurygdeoliveira** [comment]
@JorgeEduard vamos marcar uma live na próxima semana, vamos tentar resolver juntos, ok ?

**Comment by JorgeEduard** [comment]
obrigado!

Em sex., 25 de set. de 2020 às 15:06, Iury Gomes de Oliveira <
notifications@github.com> escreveu:
