### ISSUE TITLE
O Uri suporta MySql?

### ISSUE THREAD

**Issue by lhenriquedeveloper** [iurygdeoliveira/MySQL#2]
Professor, seguinte, aqui no URI ele só tá disponibilizando a resolução das questões em PostgreSQL (pelo menos pra mim), se eu usar os mesmos comandos do MySql vai dar certo?
![Capturar](https://user-images.githubusercontent.com/62040725/94301749-7e96f180-ff41-11ea-84eb-e97168610da6.JPG)

**Comment by iurygdeoliveira** [comment]
Sim, é SQL
